updated the CI steps

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,5 +18,7 @@ jobs:
         with:
           go-version: "1.23.0"
 
-      - name: Fore Failure
-        run: (exit 1)
+      # - name: Force Failure
+      #   run: (exit 1)
+      - name: Get Go version
+        run: go version
